[tool.poetry]
name = "kintree"
version = "0.3.6"
description = "Fast part creation in KiCad and InvenTree"
authors = ["Placeholder Name <placeholder@test.com>"]
license = "GPL3"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
altgraph = ">=0.17,<1.0"
certauth = ">=1.3.0,<2.0"
certifi = ">=2020.6.20,<2021.0"
cffi = ">=1.14.1,<2.0"
chardet = ">=3.0.4,<4.0"
coverage = ">=5.2.1,<6.0"
coveralls = ">=2.1.2,<3.0"
cryptography = ">=3.0,<4.0"
fake-useragent = ">=0.1.11,<1.0"
fuzzywuzzy = ">=0.18.0,<1.0"
idna = ">=2.10,<3.0"
inflection = ">=0.5.0,<1.0"
pycparser = ">=2.20,<3.0"
pyinstaller = ">=4.0,<5.0"
pyinstaller-hooks-contrib = ">=2020.7,<2021.0"
pyOpenSSL = ">=19.1.0,<20.0"
PySimpleGUI = ">=4.28.0,<5.0"
PyYAML = ">=5.3.1,<6.0"
requests = ">=2.24.0,<3.0"
requests-file = ">=1.5.1,<2.0"
retrying = ">=1.3.3,<2.0"
schematics = ">=2.1.0,<3.0"
shiboken2 = ">=5.15.0,<6.0"
six = ">=1.15.0,<2.0"
tldextract = ">=2.2.3,<3.0"
validators = ">=0.18.1<1.0"
wrapt-timeout-decorator = "^1.3.1"
python-Levenshtein = "^0.12.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
