# Coding
CODES:
  Assemblies: PCA
  Capacitors: CAP
  Circuit Protections: PRO
  Connectors: CON
  Crystals and Oscillators: CLK
  Diodes: DIO
  Inductors: IND
  Integrated Circuits: ICS
  Mechanicals: MEC
  Miscellaneous: MIS
  Modules: MOD
  Power Management: PWR
  Printed-Circuit Boards: PCB
  RF: RFC
  Resistors: RES
  Transistors: TRA
# Parents and Children Categories
CATEGORIES:
  Assemblies:
  - Printed-Circuit Board Assembly
  - Product
  Capacitors:
  - Ceramic
  - Aluminium
  - Tantalum
  - Polymer
  - Super Capacitors
  Circuit Protections:
  - TVS
  - Fuses
  - PTC
  Connectors:
  - Battery
  - Board-to-Board
  - Interface
  - Coaxial
  - FPC
  - Header
# - Wire-to-Board
# - High-Speed
# - RF
# - Power
  Crystals and Oscillators:
  - Crystals
  - Oscillators
  Diodes:
  - Standard
  - Schottky
  - Zener
  - LED
  Inductors:
  - Power
  - Ferrite Bead
# - RF
  Integrated Circuits:
  - Logic
  - Interface
  - Microcontroller
  - Memory
  - Sensor
# - SoC-CPU-GPU
# - FPGA-ASIC-CPLD
# - Driver
  Mechanicals:
  - Switch
  - Standoff
  - Nuts
  - Screws
  Miscellaneous:
  - Batteries
  Modules: null
  Printed-Circuit Boards: null
  Power Management:
  - PMIC
  - LDO
  - Buck
  - Boost
  Printed-Circuit Boards: null
  RF:
  - Chipset
  - Antenna
  - Filter
  - Shield
  Resistors:
  - Surface Mount
  - Through Hole
  - Potentiometers
  - NTC
# - Array
  Transistors:
  - N-Channel FET
  - P-Channel FET
  - NPN
  - PNP
  - Load Switches
# - N+N-Channel FET
# - N+P-Channel FET