Capacitors:
  Aluminium:
  - Aluminum Electrolytic Capacitors
  Ceramic:
  - Ceramic Capacitors
  - Ceramic
  Polymer:
  - Aluminum - Polymer Capacitors
  - Tantalum - Polymer Capacitors
  Super Capacitors:
  - Electric Double Layer Capacitors (EDLC), Supercapacitors
  Tantalum:
  - Tantalum Capacitors
Circuit Protections:
  Fuses:
  - Fuses
  PTC:
  - PTC Resettable Fuses
  TVS:
  - TVS - Diodes
Connectors:
  Board-to-Board:
  - Rectangular Connectors - Arrays, Edge Type, Mezzanine (Board to Board)
  Coaxial:
  - Coaxial Connectors (RF)
  FPC:
  - FFC, FPC (Flat Flexible) Connectors
  Header:
  - Rectangular Connectors - Headers, Male Pins
  - Rectangular Connectors - Headers, Receptacles, Female Sockets
  Interface:
  - USB, DVI, HDMI Connectors
  - Barrel - Audio Connectors
  - Memory Connectors - PC Card Sockets
  - Modular Connectors - Jacks With Magnetics
Crystals and Oscillators:
  Crystals:
  - Crystals
  Oscillators:
  - Oscillators
Diodes:
  LED:
  - LED Indication - Discrete
  - Addressable, Specialty
  Zener:
  - Diodes - Zener - Single
  __Schottky:
  - Diodes - Rectifiers - Single
  __Standard:
  - Diodes - Rectifiers - Single
Inductors:
  Ferrite Bead:
  - Ferrite Beads and Chips
  Power:
  - Fixed Inductors
Integrated Circuits:
  Interface:
  - Interface - CODECs
  Logic:
  - Logic - Translators, Level Shifters
  MCU:
  - Embedded - Microcontrollers
  Memory:
  - Memory
  Sensor:
  - Humidity, Moisture Sensors
Mechanicals:
  Switch:
  - Tactile Switches
Power Management:
  LDO:
  - PMIC - Voltage Regulators - Linear
  __Boost:
  - PMIC - Voltage Regulators - DC DC Switching Regulators
  __Buck:
  - PMIC - Voltage Regulators - DC DC Switching Regulators
RF:
  Antenna: null
  Chipset: null
  Filter:
  - Balun
Resistors:
  Surface Mount:
  - Chip Resistor - Surface Mount
  Through Hole:
  - Through Hole Resistors
Transistors:
  __N-Channel FET:
  - Transistors - FETs, MOSFETs - Single
  __NPN:
  - Transistors - Bipolar (BJT) - Single
  __P-Channel FET:
  - Transistors - FETs, MOSFETs - Single
  __PNP:
  - Transistors - Bipolar (BJT) - Single
