# Parameters
# Name: Unit
Min Output Voltage: V
Antenna Type: null
B Constant: K
Breakdown Voltage: V
Capacitance: nF
Clamping Voltage: V
Collector Gate Voltage: V
DC Resistance: mOhm
ESR: mOhm
Footprint: null
Forward Voltage: V
Frequency: Hz
Frequency Stability: ppm
Frequency Tolerance: ppm
Function Type: null
Interface Type: null
LED Color: null
Load Capacitance: pF
Locking: null
Mating Height: mm
Max Input Voltage: V
Max Output Voltage: V
Maximum Gate Voltage: V
Memory Size: null
Min Input Voltage: V
Mounting Type: null
Number of Channels: null
Number of Contacts: null
Number of Elements: null
Number of Rows: null
Orientation: null
Output Current: A
Output Type: null
Package Height: mm
Package Size: mm
Package Type: null
Pitch: mm
Polarity: null
Quiescent Current: A
RDS On Resistance: Ohm
RDS On Voltage: V
Rated Current: A
Rated Power: W
Rated Voltage: V
Saturation Current: A
Shielding: null
Standoff Voltage: V
Symbol: null
Temperature Grade: null
Temperature Range: "\xB0C"
Tolerance: '%'
Value: null
